server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservers
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: usuarios-service  # Asegura que este nombre sea correcto
    config:
      import: "optional:configserver:http://localhost:8888/"
    cloud:
      config:
        fail-fast: true #si eureka està abajo, entonces este micro tambien fallarà

  security:
    user:
      name: user
      password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90


management:
  endpoints:
    web:
      exposure:
        include: '*'
