server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: usuarios-service
          uri: lb://USUARIOS-SERVICE
          predicates:
            - Path=/usuarios/**
        - id: tareas-service
          uri: lb://TAREAS-SERVICE
          predicates:
            - Path=/tareas/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
